version: "3.2"
services:

  app:
    image: ${IMAGE}:${IMAGE_VER}
    restart: always
    networks:
      - lan
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.redirect.entryPoints=${REDIR_ENTRY}"
      - "traefik.frontend.rule=Host:${APP_SITE}"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ../../data/mmost-conf:/mattermost/config
      - ../../data/mmost:/mattermost/data
      - ../../data/mmost-plugins:/mattermost/plugins
      - ../../log/mmost:/mattermost/log
    environment:
      - MM_CONFIG=/mattermost/config/config.json
      - MM_DBNAME=${DB_USER}
      - MM_USERNAME=${DB_USER}
      - MM_PASSWORD=${DB_PASS}
      - MM_SERVICESETTINGS_SITEURL=http://${APP_SITE}

networks:
  lan:
    external:
      name: ${DCAPE_NET}
