# custom app config
# overrides DCAPE/apps/drone/dcape-app/docker-compose.yml

version: '2'

services:
  app:
    environment:
      - MM_CONFIG=/mattermost/config/config.json
      - DB_HOST=db
      - MM_DBNAME=${PGDATABASE}
      - MM_USERNAME=${PGUSER}
      - MM_PASSWORD=${PGPASSWORD}
      - MM_SERVICESETTINGS_SITEURL=http://${APP_SITE}
    volumes:
      - ${DCAPE_ROOT}/mmost/config:/mattermost/config
      - ${DCAPE_ROOT}/mmost/data:/mattermost/data
      - ${DCAPE_ROOT}/mmost/plugins:/mattermost/plugins
      - ${DCAPE_ROOT}/mmost/plugins-cl:/mattermost/client-plugins
      - ${DCAPE_ROOT}/mmost/logs:/mattermost/logs
