# app custom Makefile

# Docker repo & image name without version
IMAGE    ?= mattermost/mattermost-prod-app
# Docker image version
IMAGE_VER        ?= v5.30.1

# Hostname for external access
APP_SITE ?= chat.dev.lan
# App names (db/user name etc)
APP_NAME ?= mmost

# Enable DB usage:
# * Add DB config part to .env.sample
# * Enable db* targets
# * make db-create inside .drone-default target
USE_DB   ?= yes

# Add user config part to .env.sample
ADD_USER ?= no

# ------------------------------------------------------------------------------
# app custom config

DCAPE_ROOT   ?= /opt/dcape/var

# ------------------------------------------------------------------------------
# .env template (custom part)
# inserted in .env.sample via 'make config'
define CONFIG_CUSTOM
# ------------------------------------------------------------------------------
# app custom config, generated by make config
# db:$(USE_DB) user:$(ADD_USER)

# Path to /opt/dcape/var. Used only outside drone
#DCAPE_ROOT=$(DCAPE_ROOT)

endef

# ------------------------------------------------------------------------------
# Find and include DCAPE/apps/drone/dcape-app/Makefile
DCAPE_COMPOSE   ?= dcape-compose
DCAPE_MAKEFILE  ?= $(shell docker inspect -f "{{.Config.Labels.dcape_app_makefile}}" $(DCAPE_COMPOSE))
ifeq ($(shell test -e $(DCAPE_MAKEFILE) && echo -n yes),yes)
  include $(DCAPE_MAKEFILE)
else
  include /opt/dcape-app/Makefile
endif

# -----------------------------------------------------------------------------
## Custom app targets
#:


## create and chown mattermost volumes
mmost-dirs:
	for f in config data plugins plugins-cl logs ; do mkdir -pv $(DCAPE_ROOT)/mmost/$$f ; done
ifeq (true, $$DRONE)
	chown -R 2000:2000 $(DCAPE_ROOT)/mmost/
else
	sudo chown -R 2000:2000 $(DCAPE_ROOT)/mmost/
endif
